### ISSUE TITLE
Only 1 Joycon will be sent to the server

### ISSUE THREAD

**Issue by Searith** [carl-anders/slimevr-wrangler#1]
The default SlimeVR server can only take up to 2 rotational inputs from each IP. One from the packet type 1 and packet type 16. Since this seems to only use packet type 1 it sends all the rotational data to one tracker. Adding an option for every pair of joycons to have a different IP could allow for redirecting the packets from another device like a phone.

**Comment by carl-anders** [comment]
Hi. This project hasn't been released yet

**Comment by carl-anders** [comment]
I have added support for more than one Joycon in the 0.2 release. Closing issue.
