### ISSUE TITLE
Software won't launch

### ISSUE THREAD

**Issue by candygamer-YT** [carl-anders/slimevr-wrangler#12]
I had recently factory reset my computer and I had installed VRchat and steam vr. But for some reason the program keeps crashing and won't let me launch it. Any Ideas of what may be causing this.

**Comment by carl-anders** [comment]
Yeah there's no way to help without any more information than this. Does the console give any information? You can probably get more help in the discord https://discord.com/channels/817184208525983775/932234894518677534
