### ISSUE TITLE
steam joycon support

### ISSUE THREAD

**Issue by ssTalt** [carl-anders/slimevr-wrangler#13]
the newly steam joycon support kinda screw up the software on detecting the joycon 
when i have my steam opened the joycon are automaticly connect to steam and unable to search
as trackers with slimevr wrangler,need some solution on that (maybe disable joycon connected as steam controller)
the only way to pair controller as tracker is when the steam is closed

**Comment by ssTalt** [comment]
everytime i open my steam the controller are automaticly pair on steam and whenever the tracking is lose i have to turn steam off and reset everything up again before opening steam

**Comment by carl-anders** [comment]
There is a manual solution found here: https://discord.com/channels/817184208525983775/932234894518677534/1011661239623102576

I'm hoping to add support for wrangler to change the steam config automatically.

**Comment by chakkachai** [comment]
> There is a manual solution found here: https://discord.com/channels/817184208525983775/932234894518677534/1011661239623102576
> 
> I'm hoping to add support for wrangler to change the steam config automatically.

I got this issue too. This solution link it not work. I cannot see any discord channel. Can you please reply it here?
Thank you so much.

**Comment by carl-anders** [comment]
With the newest update the app detects if the steam controller blacklist is not correct, and can change this config to fix the issue.
