### ISSUE TITLE
Pro Controller Support?

### ISSUE THREAD

**Issue by Rangeclone** [carl-anders/slimevr-wrangler#3]
The pro controller can defo connect via bluetooth but I also think it has the same IMU's as joycons as I do remember being able to physically turn the controller in mario kart to steer?

(I'm not demanding you add this right away, its just a suggestion and I think what you're working on is really cool and will help bring slime VR to alot more people)

**Comment by carl-anders** [comment]
I don't have a pro controller so I can't test why it doesn't work. You or someone else are free to add the support to enable this.

**Comment by carl-anders** [comment]
Closing this. Apparently according to people that have a pro controller it also works for slimevr wrangler.
