### ISSUE TITLE
Slimewrangler app/Slimewrangler owotrack implementation

### ISSUE THREAD

**Issue by kodacomusic** [carl-anders/slimevr-wrangler#30]
My computer has issues connecting the joycons through bluetooth although its 4.2 bluetooth. But my phone connects flawlessly and it would be cool if there was an app for slimewrangler for android or even just have it implemented onto owotrack’s app.

**Comment by carl-anders** [comment]
Hi. This is not owotrack. To ask them for support, go to their discord: https://discord.gg/Xdb4knmEge
