### ISSUE TITLE
program refuses to show more than two controllers at a time

### ISSUE THREAD

**Issue by staticanimal** [carl-anders/slimevr-wrangler#31]
i am trying to use a pro controller and two joy-cons with this program and can not get more than two of the three to show up in slimevr wrangler, no matter how much time i spend dis- and reconnecting the controllers. every controller is connecting fine to my computer and even with all three connected simultaneously they are all fully functional and usable. in fact, i've tested a fourth controller and noticed not even the slightest drop in functionality for any single one of them. this is immensely irritating, especially with it being the only tool of its kind and no functional solutions around.

i would like to reiterate: my setup is completely functional. the aforementioned issues i am experiencing are exclusively on the program's end.

**Comment by staticanimal** [comment]
> Hi. This is probably due to your Bluetooth adapter, some only support two controllers.
> 
> Also, support questions should go to the discord: https://discord.gg/slimevr (#joycons channel)

this is not a support question. this is an issue with the software. it would only make sense for it to be posted here.

additionally: after further testing i was able to get all three controllers to show up in the software, fully functional as well.
this is a software issue that requires looking into.

again, highly unlikely to be a hardware issue.

**Comment by carl-anders** [comment]
It works for up to 6-7 devices for everyone with a high end Bluetooth adapter. I'm sorry to hear your adapter has issues, but this is a common question in the support discord.
