### ISSUE TITLE
(Windows 11) Joycons IMU "die" and become super slow after a short "Laggy IMU" error

### ISSUE THREAD

**Issue by BuyMyMojo** [carl-anders/slimevr-wrangler#33]
So when I connect a single joycon it will work perfectly for a few minutes and then it's roll, pitch and yaw slow down to an absolute crawl after the Status says "Laggy IMU" for a split seccond and then goes back to "Healthy", or it will happen when two are connected, one connects right after the other. it's a very weird issue that keeps appearing and makes using node wrangler unusable. 

I've tried it with the reg and blue joycons from my launch switch and a brand new pair of green and pink ones and the issues persists. I event tested versions 0.8 and 0.9 and the issue appears.

I mannaged to record of gif of one work and one not working, I am moving both joycon the exact same amount at the same time for this entire gif:
![Rip Wrangler](https://github.com/carl-anders/slimevr-wrangler/assets/46948241/729ed46b-4ea1-43a6-9c65-b7dc98162b99)

**Comment by BuyMyMojo** [comment]
Okay I have found out it is Steam stealing the controller, I messed around with disabling Steam Input on individual controllers and it semi-worked, with the latest steam update there is no longer the hide controller option in the controller settings.

For me the auto blacklist thing when first starting wrangler did not work

**Comment by carl-anders** [comment]
Support questions should be directed to the Discord. I will investigate if the recent steam changes have changed anything tho. Closing issue.
