### ISSUE TITLE
When connecting Joycons to the wrangler, One side will connect just fine while the other will connect to windows but not to slimevr.

### ISSUE THREAD

**Issue by BluRazzberry** [carl-anders/slimevr-wrangler#41]
I have 6 Joycons here I am attempting to use for FBT. I was attempting to put all 6 on the wrangler at the same time, however it seems I can only connect 3 of them at time max. The only correlation I can put to this is that all the controllers that seem to connect are on the same side, left or right controllers. I can switch between connecting all of each type, but I can never connect both at once. I have already attempted to connect them in alternation, Attempted to connect them all to windows before launching the wrangler, attempted to connect them by the pairs they were bought in, everything. I know it's in alpha, but I have gotten 5 controllers connected off of a fluke when I freshly downloaded the software, so I have no idea why it's not connecting.

**Comment by tailsman2000** [comment]
Having the same issue as well when trying to connect 4. Seemingly have had no issues connecting all my joycons via bluetooth+betterjoy but wrangler only recognizes 2 of the same side

**Comment by someone465** [comment]
did you even find a fix?

**Comment by AlWoGa1114** [comment]
Found a workaround. I set up 2 pairs of joycons on my desktop and the 5th joycon on my laptop. On the secondary device you'll have to change the connect IP to the IPv4 of the SlimeVR server. It adds 2ms of delay this way but it works. You only need Wrangler on the second device.
