### ISSUE TITLE
When opened noticable lag occurs / Joycons randomly disconnect

### ISSUE THREAD

**Issue by MrCanKnotNot** [carl-anders/slimevr-wrangler#42]
I am unsure of what is causing this "lag" in particular as each time I open the software my computer freezes in a pattern even when I try to pair my joy con. the one time I got it to not do this was starting up the sever and pairing a joy con ( which now isn't even connecting to my PC for some reason ). and I don't know if this has anything to do with it but after setting them up I went to pair them in slimevr and a controller had turned off. I reconnected it but it and another controller just disconnected after and as I said I have tried twice after that to reconnect them but they aren't connecting via bluetooth.

**Comment by carl-anders** [comment]
Hi. Please direct your help requests to the discord, thanks.
https://discord.com/invite/slimevr
