### ISSUE TITLE
Significant Yaw drift : calibration feature?

### ISSUE THREAD

**Issue by Andrope** [carl-anders/slimevr-wrangler#8]
My left Joycon drifts at a constant rate on the Yaw axis. I was wondering if there's a way to implement a way to compensate any drift by doing a calibration.
Simply asking the user to lay their Joycons flat for a few seconds, detecting the drifts in degrees/second, and sending compensated gyro data to SlimeVR. Or simply having a manual calibration tool where users can at least input the compensation themselves.

Here's a video that demonstrates the effect (doesn't happen on the right Joycon so it's not a Wrangler issue) : https://www.youtube.com/shorts/cyWSeClkVUs

**Comment by carl-anders** [comment]
You will have to calibrate it using a Nintendo Switch. If you don't have one borrow one from a friend.

For support issues please ask in the joycon channel in the SlimeVR discord: https://discord.com/channels/817184208525983775/932234894518677534

Discord: https://discord.gg/SlimeVR
